version: '3.7'
networks:
    backend:
      name: app
      driver: bridge
volumes:
  postgres-data:
        
services:
  db:
    image: "postgres:13"
    container_name: sbpostgres-db
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sqlscripts/inittable.sql:/docker-entrypoint-initdb.d/inittable.sql
    networks:
      - backend
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sergiob
      POSTGRES_USER: sergiob
      POSTGRES_PASSWORD: sergioUnix1
      PGDATA: /var/lib/postgresql/pgdata
  
